# -*- coding: utf-8 -*-
"""Python Session #1_ Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_6CX-MHnmrIbZStwRlgGisC6KrU-8lsf
"""

print("Hello Python")

print("Happy new year 2024")

print(4 + 8)
print(34 + 56)
print(34 - 56)
print(4 * 7)
print(8 * 10)

print(11 / 2) #float divison 
print(11 // 2) #integer divison

print(11 % 2)
print(76 % 5)

print(-3 * 5)

print(3 ** 5)
print(10 ** 4)

print(-13 / 5)

print(-13 % 5)

print(13 % -5)

#operator precedence
print(10 ** 2 * 7 - 3)
print(10 ** (2 * 7) - 3)
print(10 ** ((2 * 7) - 3))

a = 4557698
b = a ** 7
print(b)
c = a ** 11
print(c)
d = a ** 156
print(d)

a = 10
b = 5
print(a, b)
a += b
print(a, b)
a *= b
print(a, b)

x = 10
x += 1
print(x)

a = 45
b = 89
print(a == b, a == b - 10, a + 24 == b, a < b, a > b , a >= b)

a < b < 90

a < b < 78

a = 14.98
b = 20.99
c = a + b
print(c)
d = a - b
print(d)
e = a * b
print(e)
f = a / b
print(f)

print(2/6)
print(2/3)

print(12.9 * 3.6 == 46.44)

print(12.9 * 3.6 - 46.44)

print(abs(12.9 * 3.6 - 46.44) <= 0.0000001)

2.5 * 4.0 == 10

z = 2 - 3j
print(z)
print(z.real)
print(z.imag)
print(abs(z))

x = 6 + 12j
print(z + x)
print(z - x)
print(z * x)
print(z / x)